# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 375a6453e64b905a257e00caed3f4f9ce131fb1a19e88cfe47ddd5a300666a72c6a8e12d386ce6967db631a531aa2fba63e2cd4557a50a8fd718efbc21da4bdb

test:
  secret_key_base: cb4959b9779d9fc82dfcda214d40888be25fc6dfb2dee6b8eac6cfa0e11d2e5f95bc7bf437c64ba1b469c63ef4ca3fe924150b8f3cf41d439258da0b0fff4a82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
